name: Codeceptjs

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        config: [desktop, mobile]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn
          yarn global add wait-on
      - name: Start dev server
        run: yarn start &
      - name: Run tests
        run: wait-on http://localhost:8080 && yarn codecept:${{ matrix.config }} run --steps
        env:
          CI: true
