name: lhci
on: [push]
jobs: 
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, build
        run: |
          yarn install
          yarn run build
      - name: install Lighthouse CI
        run: |
          sudo yarn global add @lhci/cli@0.7.x http-server
      - name: run Lighthouse CI
        run: |
          lhci autorun