name: Lighthouse

on:
  workflow_run:
    workflows: ['Firebase Preview']
    types:
      - completed

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: install Lighthouse CI
        run: |
          sudo yarn global add @lhci/cli@0.12.x http-server
      - name: run Lighthouse CI
        with:
          LHCI_SERVER_BASE_URL: '${{ github.event.client_payload.url }}'
        run: lhci autorun
