name: Lighthouse

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Fill preview link'

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Lighthouse CI
        run: sudo yarn global add @lhci/cli@0.12.x http-server
      - name: Run Lighthouse CI
        run: lhci autorun --collect.url=${{ github.event.inputs.url }}?app-config=gnnuzabk --config=./lighthouserc.js
